eureka:
  instance:
    prefer-ip-address: true
  client: 
    fetch-registry: true
    register-with-eureka:  true
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost:8762/eureka}
okta:
  oauth2:
    issuer: https://dev-35001248.okta.com/oauth2/default
    audience: api://default
