server:
  port: 8082
spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:9296
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/online-shop
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: orderdb

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      domain-zone: http://{EUREKA_SERVER_ADDRESS:localhost:6761/eureka}