server:
  port: 8082
spring:
  application:
    name: order-service
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/online-shop
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: orderdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-35001248.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa8b7kgdzJeGHv1S5d7
            client-secret: ObJYY5tMePknj4FXsIRF6qOiEKLv5saGH90QIldl
        provider:
          okta:
            issuer-uri: https://dev-35001248.okta.com/oauth2/default

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failer-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-windows-size: 10
        sliding-windows-type: COUNT-BASED